site_name: ""
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://codelabs.se
  consent:
    title: Kakor
    description: >-
      Vi använder kakor för att förbättra din upplevelse av vår webbplats. Genom att fortsätta använda vår webbplats godkänner du vår användning av kakor.
theme:
  name: material
  lang: sv
  logo: assets/codelabs.svg
  font:
    text: Roboto
  features:
    - header.autohide
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode